name: bisect

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string

jobs:
  test:
    runs-on: [ "ubuntu-latest" ]
    container:
      image: ${{ inputs.image }}
      options: --user root
    steps:
      - name: Create directories
        run: |
          sudo mkdir -p ${GITHUB_WORKSPACE}
          sudo chown -R build:build ${GITHUB_WORKSPACE}

      - name: Check out rspamd source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rspamd/rspamd
          path: src

      - name: Check out our source code
        uses: actions/checkout@v4
        with:
          path: self

      - name: Backup tests
        run: |
          cd ${GITHUB_WORKSPACE}/src
          cp -R test test.orig

      - name: Run bisect
        run: |
          cd ${GITHUB_WORKSPACE}/src
          git bisect start
          git bisect bad
          git bisect good 126584384ea4d7e26289771b4d663e796f2f65f6
          git bisect run ${GITHUB_WORKSPACE}/self/build_and_test.sh
